WIFI = "home,EmeraldWiFi,rejoice27;pantry,MiFi8000-C1DE,9df7061f"
SENSORS = "Pantry_Standing_Freezer_East,GP5;Pantry_Standing_Freezer_West,GP13"
EXTRA_HOTS="GP4,GP12"

TOKEN_URL="https://raw.githubusercontent.com/okielife/TempSensors/nekot/nekot"

KNOWN_SENSOR_IDS=[
    "Must match the config in https://github.com/okielife/TempSensors/blob/main/_data/config.json",
    "Emerald_Garage_Fridge",
    "Emerald_Garage_Freezer",
    "Pantry_Garage_Freezer",
    "Pantry_South_Room_Top_Bottom_Freezer",
    "Pantry_South_Room_Top_Bottom_Fridge",
    "Pantry_Dining_Deep_Freezer",
    "Pantry_Standing_Freezer_East",
    "Pantry_Standing_Freezer_West",
    "Pantry_Entry_Top_Bottom_Fridge",
    "Pantry_Entry_Side_By_Side_Freezer",
    "Pantry_Entry_Side_By_Side_Fridge",
    "Pantry_West_Standing_Freezer",
    "Emerald_Kitchen_Freezer",
    "Emerald_Kitchen_Fridge"
  ]
